package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/goccy/go-yaml"
)

const recoveryFilename = ".mksvc-recovery.json"

type generatedFile struct {
	name   string
	data   []byte
	mode   os.FileMode
	remove bool
	marker string
}

type generatedTemplate struct {
	name     string
	template *template.Template
	rotation bool
}

type fileSnapshot struct {
	Name   string      `json:"name"`
	Data   []byte      `json:"data"`
	Mode   os.FileMode `json:"mode"`
	Exists bool        `json:"exists"`
}

func (cfg *ServiceConfig) renderFiles(configName, serviceName string) ([]generatedFile, error) {
	templates := []generatedTemplate{
		{serviceName, ServiceTmpl, false},
		{cfg.Name + ".conf", UserTmpl, false},
		{"setup.sh", SetupTmpl, false},
		{"uninstall.sh", UninstallTmpl, false},
		{cfg.Name + "_logs.conf", LogrotateTmpl, true},
	}

	files := make([]generatedFile, 0, len(templates)+1)

	marker := "# Generated by mksvc for " + cfg.Name

	for _, item := range templates {
		file := generatedFile{name: item.name, mode: 0644}

		if item.rotation && cfg.Journald {
			file.remove = true
			file.marker = marker
		} else {
			var buffer bytes.Buffer

			err := item.template.Execute(&buffer, cfg)
			if err != nil {
				return nil, fmt.Errorf("render %s: %w", item.name, err)
			}

			file.data = buffer.Bytes()
		}

		files = append(files, file)
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}

	// Publish saved settings last. A journal permits rollback of the whole set.
	files = append(files, generatedFile{name: configName, data: data, mode: 0600})

	return files, nil
}

func beginGeneration(directory string) (*os.File, error) {
	info, err := os.Lstat(directory)
	if os.IsNotExist(err) {
		err = os.Mkdir(directory, 0755)
		if err != nil && !os.IsExist(err) {
			return nil, err
		}

		info, err = os.Lstat(directory)
	}

	if err != nil {
		return nil, err
	}

	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s must be a real directory", directory)
	}

	lockPath := filepath.Join(directory, ".mksvc.lock")

	err = checkRegularTarget(lockPath)
	if err != nil {
		return nil, err
	}

	lock, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return nil, err
	}

	err = lockFile(lock)
	if err != nil {
		lock.Close()

		return nil, fmt.Errorf("cannot lock generation (another writer may be active): %w", err)
	}

	err = recoverGeneration(directory)
	if err != nil {
		lock.Close()

		return nil, err
	}

	return lock, nil
}

func commitGeneration(directory string, files []generatedFile, write func(string, []byte, os.FileMode) error) error {
	snapshots := make([]fileSnapshot, 0, len(files))

	// Complete rendering and preflight every target before changing any output.
	for _, file := range files {
		path := filepath.Join(directory, file.name)

		err := checkRegularTarget(path)
		if err != nil {
			return err
		}

		snapshot := fileSnapshot{Name: file.name}

		info, err := os.Stat(path)
		if err == nil {
			snapshot.Exists = true
			snapshot.Mode = info.Mode().Perm()
			snapshot.Data, err = os.ReadFile(path)
		}

		if err != nil && !os.IsNotExist(err) {
			return err
		}

		if file.remove && snapshot.Exists {
			header, _, _ := bytes.Cut(snapshot.Data, []byte("\n"))
			if string(bytes.TrimSuffix(header, []byte("\r"))) != file.marker {
				return fmt.Errorf("refusing to remove unrecognized generated file %s", path)
			}
		}

		snapshots = append(snapshots, snapshot)
	}

	data, err := json.Marshal(snapshots)
	if err != nil {
		return err
	}

	journalPath := filepath.Join(directory, recoveryFilename)

	err = writeFileAtomic(journalPath, data, 0600)
	if err != nil {
		return err
	}

	for _, file := range files {
		path := filepath.Join(directory, file.name)

		if file.remove {
			err = removeGeneratedFile(path)
		} else {
			err = write(path, file.data, file.mode)
		}

		if err != nil {
			recoveryErr := recoverGeneration(directory)

			return errors.Join(fmt.Errorf("publish %s: %w", file.name, err), recoveryErr)
		}
	}

	return removeGeneratedFile(journalPath)
}

func recoverGeneration(directory string) error {
	journalPath := filepath.Join(directory, recoveryFilename)

	err := checkRegularTarget(journalPath)
	if err != nil {
		return err
	}

	data, err := os.ReadFile(journalPath)
	if os.IsNotExist(err) {
		return nil
	}

	if err != nil {
		return err
	}

	var snapshots []fileSnapshot

	err = json.Unmarshal(data, &snapshots)
	if err != nil {
		return fmt.Errorf("read generation recovery journal: %w", err)
	}

	// Validate every journal path before restoring anything, including journals
	// left on another OS. Backslashes must not become separators after a move.
	for _, snapshot := range snapshots {
		if snapshot.Name == "" || snapshot.Name == "." || snapshot.Name == ".." || strings.ContainsAny(snapshot.Name, "/\\:") || strings.HasPrefix(snapshot.Name, ".mksvc") {
			return fmt.Errorf("invalid recovery filename %q", snapshot.Name)
		}
	}

	for _, snapshot := range snapshots {
		path := filepath.Join(directory, snapshot.Name)

		if snapshot.Exists {
			err = writeFileAtomic(path, snapshot.Data, snapshot.Mode.Perm())
		} else {
			err = removeGeneratedFile(path)
		}

		if err != nil {
			return fmt.Errorf("recover %s (journal retained for retry): %w", snapshot.Name, err)
		}
	}

	return removeGeneratedFile(journalPath)
}

func removeGeneratedFile(path string) error {
	err := checkRegularTarget(path)
	if err != nil {
		return err
	}

	err = os.Remove(path)
	if os.IsNotExist(err) {
		return nil
	}

	if err != nil {
		return err
	}

	return syncDirectory(filepath.Dir(path))
}
