name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos:   [windows, linux, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build ${{ matrix.goos }}_${{ matrix.goarch }}
      id: build
      uses: coalaura/build@v1
      with:
        os: ${{ matrix.goos }}
        arch: ${{ matrix.goarch }}
        optimization: compatible
        generate: 'false'
        output: build/mksvc_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        go-flags: |
          -trimpath
          -buildvcs=false
          -ldflags=-s -w -X main.Version=${{ github.ref_name }}

    - name: Sign ${{ matrix.goos }}_${{ matrix.goarch }}
      id: sign
      uses: coalaura/sign@v1
      with:
        path: ${{ steps.build.outputs.path }}
        key: ${{ secrets.SIGNING_KEY }}
        passphrase: ${{ secrets.SIGNING_KEY_PASSPHRASE }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mksvc_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}
        path: ${{ steps.sign.outputs.path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Flatten artifacts
      run: |
        mkdir -p ./build
        find ./artifacts -type f -exec cp {} ./build/ \;

    - name: Create checksums
      working-directory: ./build
      run: sha256sum mksvc_* > checksums.txt

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/**
        name: "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
